import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

DEBUG_MODE = os.getenv("DEBUG_MODE")

SQLALCHEMY_DATABASE_URL = os.getenv("SQLALCHEMY_DATABASE_URL")

KEYCLOAK_SERVER_URL = os.getenv("KEYCLOAK_SERVER_URL", "http://localhost:8080")
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM", "mos-realm")
KEYCLOAK_CLIENT_ID = os.getenv("KEYCLOAK_CLIENT_ID", "mos-backend")
KEYCLOAK_CLIENT_SECRET = os.getenv("KEYCLOAK_CLIENT_SECRET")
KEYCLOAK_ADMIN = os.getenv("KEYCLOAK_ADMIN", "admin")
KEYCLOAK_ADMIN_PASSWORD = os.getenv("KEYCLOAK_ADMIN_PASSWORD", "admin")
KEYCLOAK_ADMIN_CLIENT_ID = os.getenv("KEYCLOAK_ADMIN_CLIENT_ID", "admin-cli")
KEYCLOAK_ADMIN_CLIENT_SECRET = os.getenv("KEYCLOAK_ADMIN_CLIENT_SECRET")
KEYCLOAK_ADMIN_REALM = os.getenv("KEYCLOAK_ADMIN_REALM", "master")
KEYCLOAK_ACCESS_COOKIE_NAME = os.getenv("KEYCLOAK_ACCESS_COOKIE_NAME", "kc_access_token")
KEYCLOAK_REFRESH_COOKIE_NAME = os.getenv("KEYCLOAK_REFRESH_COOKIE_NAME", "kc_refresh_token")
KEYCLOAK_COOKIE_SECURE = os.getenv("KEYCLOAK_COOKIE_SECURE", "false").lower() == "true"
KEYCLOAK_COOKIE_SAMESITE = os.getenv("KEYCLOAK_COOKIE_SAMESITE", "lax")
KEYCLOAK_COOKIE_DOMAIN = os.getenv("KEYCLOAK_COOKIE_DOMAIN")
